CREATE DATABASE IF NOT EXISTS Genshin;

CREATE TABLE CHARACTER (
	NAME varchar(20) NOT NULL PRIMARY KEY,
	HP int NOT NULL,
	ATK int NOT NULL,
	DEF int NOT NULL,
	LV int NOT NULL,
	SKILL_1 int NOT NULL,
	SKILL_2 int NOT NULL,
	SKILL_3 int NOT NULL

);

CREATE TABLE SKILL (
	SKILL_ID int NOT NULL PRIMARY KEY,
	EFFECT_ID int NOT NULL,
	LV int NOT NULL
);

-- Note: for simplicity only, all percentage will only keep the number before the "%" 
CREATE TABLE ATTACK(
	ATTACK_ID int NOT NULL PRIMARY KEY,
	1ST float NOT NULL,
	2ND float NOT NULL,
	3RD float NOT NULL,
	4TH float NOT NULL,
	5TH float NOT NULL,
	CHARGED float NOT NULL
);

/* DEFEND (DMG ABSORPTION) CALCULATE BASED ON BASE * R + B
 * E.G. NOELLE'S DMG ABSORPTION  AT SKILL LEVEL 1= DEF (BASE) * 160% (R) + 769 (B)
 * CALCULATION ON HEALING USES THE SAME FORMULA */
CREATE TABLE DEFEND(
	DEFEND_ID int NOT NULL PRIMARY KEY,
	BASE varchar(10) NOT NULL,
	R float NOT NULL,
	B int NOT NULL
);

CREATE TABLE CURE(
	CURE_ID int NOT NULL PRIMARY KEY,
	BASE varchar(10) NOT NULL,
	R float not null,
	B int NOT NULL
);

