USE GENSHIN;

INSERT INTO SKILL (NAME, LV) VALUES ("Oceanborne", 4),
				    ("Tidecaller", 5),
				    ("Stormbreaker",4),
				    ("Wind Spirit Creation", 4),
				    ("6308", 4),
				    ("75",4),
				    ("Maid", 5),
				    ("Breastplate", 5),
				    ("Sweeping Time", 5),
				    ("Dance on Fire", 3),
				    ("Sweeping Fervor", 3),
				    ("Riff Revolution", 3),
				    ("Dough-Fu", 5),
				    ("Guoba Attack", 5),
				    ("Cross Fire", 5),
				    ("Seal of Approval", 4),
				    ("Signed Edict", 4),
				    ("Proviso", 4),
				    ("Origin", 3),
				    ("Transcendence: Baleful Omen", 3),
				    ("Secret Art: Musou Shinsetsu",3),
				    ("Lightning Touch",5),
				    ("Violet Arc", 5),
				    ("Lightning Rose",4),
				    ("Whisper of Water", 4),
				    ("Let the Show Begin", 4),
				    ("Shining Miracle",4),
				    ("Katzlein Style",4),
				    ("Icy Paws", 4),
				    ("Signatur Mix",4),
				    ("Shuumatsuban Ninja Blade",1),
				    ("Yoohoo Art: Fuuin Dash",1),
				    ("Yoohoo Art: Mujina Flurry",1),
				    ("Cloud-Grazing Strike", 1),
				    ("Opening Flourish",1),
				    ("Cliffbreaker's Banner",1),
				    ("Sharpshooter", 1),
				    ("Explosive Puppet",1),
				    ("Fiery Rain",1);

SELECT * FROM SKILL;
